export type TInventoryItem = {
  _id: string;
  title: string;
  slug: string;
  thumbnail: string;
  price: number;
  stockQuantity: number;
  galleryImages: string[];
  brand: string;
  model: string;
  partNumber: string;
  color: string;
  backspacing: string;
  offset: string;
  diameter: string;
  width: string;
  hubBore: string;
  loadRating: string;
  wheelExposedLugs: string;
  wheelMaterial: string;
  weight: number;
  wheelStructure: string;
  wheelSpokeNumber: number;
  boltPatterns: string[];
  trueDirectional: string;
  relatedVideos: string[];
  category: string;
  categoryId: string | null;
  sku: string;
  manufacturer_part_number: string;
  tire_size: string;
  tire_description: string;
  tire_manufacturer: string;
  msrp: number;
  map_price: number;
  load_index: string;
  speed_rating: string;
  upc: string;
  section_width: string;
  series: string;
  rim_diameter: string;
  tire_diameter_actual: string;
  image_url: string;
  min_width_in: number;
  max_width_in: number;
  max_load: number;
  division: string;
  inv_order_type: string;
  display_model_no: string;
  tread_depth: string;
  ply: string;
  construction_type: string;
  terrain: string;
  max_load_dual: number;
  max_pressure: number;
  approved_rim_width: string;
  utqg: string;
  treadwear: string;
  traction: string;
  temperature: string;
  source_country: string;
  mileage_warranty: string;
  product_desc: string;
  size_desc: string;
  lug_count: number;
  bolt_pattern_metric: string;
  bolt_pattern_standard: string;
  centerbore: string;
  rear_only: boolean;
  tpms_compatible: boolean;
  shipping_weight: number;
  brand_cd: string;
  brand_desc: string;
  display_style_no: string;
  style: string;
  finish_warranty: string;
  structural_warranty: string;
  smallest_bolt_pattern: string;
  largest_bolt_pattern: string;
  min_lug_count: number;
  max_lug_count: number;
  open_end_cap: boolean;
  rivet_part_no: string;
  rivet_quantity: number;
  flow_formed: boolean;
  forged: boolean;
  two_piece: boolean;
  steel_wheel: boolean;
  bead_lock: boolean;
  patent: string;
  lip_depth: string;
  material: string;
  prop65_chemical1: string;
  prop65_chemical2: string;
  prop65_chemical3: string;
  image_url1: string;
  createdBy: string | null;
  updatedBy: string | null;
  deletedBy: string | null;
  isDelete: boolean;
  deletedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
export type GProduct = {
  id: number;
  slug: string;
  ymm: {
    title: string;
    model: string;
  };
  image: string;
  wheel: {
    title: string;
    size: string;
  };
  tire: {
    title: string;
    size: string;
  };
};
