import { CheckoutProvider } from "@/context/CheckoutContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import Footer from "./components/footer/footer";
import DiscountBanner from "./components/header/discount-banner";
import Header from "./components/header/header";
import TopHeader from "./components/header/topheader";
import StoreProvider from "./globalRedux/store-provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ktc Audio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col justify-between antialiased`}
      >
        <StoreProvider>
          <CheckoutProvider>
            <TopHeader />
            <Header />
            <DiscountBanner />
            <main className="flex-1">{children}</main>
            <Footer />
            <Toaster richColors />
          </CheckoutProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
